### ISSUE TITLE
Projects being created are NOT web projects

### ISSUE THREAD

**Issue by GoranHalvarsson** [LaubPlusCo/helix-msbuild-example#1]
Noticed that projects being created are standard c# lib projects. That means no help adding razor view, controllers etc. 
![Issue](https://user-images.githubusercontent.com/726479/54472472-3124ba80-47c9-11e9-90a8-e5940db39e5b.png)

**Comment by anderslaub** [comment]
Hi @GoranHalvarsson 

If you miss these shortcuts and also the ability to right-click > Publish on files you can simply declare a specific <ProjectTypeGuid> either in the individual .csproj files or in a .props file. Sidenote; notice that you can now just right click on the project and edit the csproj file directly in Visual Studio without unloading/reloading project.

An (old) list of project type guids can be seen here: https://www.codeproject.com/Reference/720512/List-of-Visual-Studio-Project-Type-GUIDs

By using one of the asp.net project types you should also get the Publish File option on all <Content> files in the project. 

Let me know if you experience any build related issues when changing project type. I have not yet played around with it myself. I almost never use these quick links anyway.
